### ISSUE TITLE
ModuleNotFoundError: No module named 'scripts.retrain--output_graph=tf_files/retrained_graph'

### ISSUE THREAD

**Issue by hunaidkhan2000** [MauryaRitesh/Face_ID#1]
hi Ritesh,
when i run code python -m scripts.retrain--output_graph=tf_files/retrained_graph.pb--output_labels=tf_files/retrained_labels.txt --architecture=inception_v3 --image_dir=tf_files/images . 

**i  got the following error :-** 
D:\Analytics\Face_ID>python -m scripts.retrain--output_graph=tf_files/retrained_graph.pb--output_labels=tf_files/retrained_labels.txt --architecture=inception_v3 --image_dir=tf_files/images
D:\anaconda5.1\python.exe: Error while finding module specification for 'scripts.retrain--output_graph=tf_files/retrained_graph.pb--output_labels=tf_files/retrained_labels.txt' (ModuleNotFoundError: No module named 'scripts.retrain--output_graph=tf_files/retrained_graph')

Can you help me out?

**Comment by MauryaRitesh** [comment]
@hunaidkhan2000 You did not put SPACE between the arguments of the script.
E.G., you should use like:
python -m scripts.retrain --output_graph=tf_files/retrained_graph.pb --.... and so on.
Basically, you need to write the following to run the script without any error:

**
python -m scripts.retrain --output_graph=tf_files/retrained_graph.pb --output_labels=tf_files/retrained_labels.txt --architecture=inception_v3 --image_dir=tf_files/images
**

**Comment by hunaidkhan2000** [comment]
i found out the issue in my python environment. I am using anaconda and
Python -m is not recognised in my CMD do u have any idea why ?

**Comment by MauryaRitesh** [comment]
@hunaidkhan2000 Open the scripts folder and CUT all of the files and PASTE them in the FACE_ID directory.
Now open CMD and just hit:

python retrain.py  --output_graph=tf_files/retrained_graph.pb --output_labels=tf_files/retrained_labels.txt --architecture=inception_v3 --image_dir=tf_files/images

It should go fine for you!

**Comment by hunaidkhan2000** [comment]
finally i did using the same method as you have mentioned . But wanted to
know why python - m is not working my machines? do you have any idea?or is
there anything we need to add in path?

**Comment by MauryaRitesh** [comment]
@hunaidkhan2000 Switching from Python 2.7.12 to Python 3.5.3 or higher removes the issue. So perhaps this is not a tensorflow issue but this is your machine's issue!
BTW I wanted to ask whether you encountered any issue while training or it does went without any further errors?

**Comment by hunaidkhan2000** [comment]
i use python 3.6 and after that i got this issue -
ERROR:tensorflow:Image directory 'tf_files/images' not found.
Traceback (most recent call last):
  File "scripts\retrain.py", line 1326, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File
"D:\anaconda5.1\lib\site-packages\tensorflow\python\platform\app.py", line
126, in run
    _sys.exit(main(argv))
  File "scripts\retrain.py", line 989, in main
    class_count = len(image_lists.keys())
AttributeError: 'NoneType' object has no attribute 'keys'

**Comment by MauryaRitesh** [comment]
@hunaidkhan2000 Have you CLONED this REPOSITORY to your machine???
Please make sure that you did so and run the script from the main directory, i.e., FACE_ID.
And watch the video carefully so that you don't encounter any further issues!

**Comment by hunaidkhan2000** [comment]
yes i followed every step of the video , still getting this error

**Comment by MauryaRitesh** [comment]
@hunaidkhan2000 CUT all the FILES of the SCRIPTS FOLDER and PASTE them in the Face_ID directory, now open CMD and type:
    python retrain.py --output_graph=tf_files/retrained_graph.pb -- 
    output_labels=tf_files/retrained_labels.txt --architecture=inception_v3 --image_dir=tf_files/images

**Comment by hunaidkhan2000** [comment]
already tried that still getting this error

ERROR:tensorflow:Image directory 'tf_files/images' not found.
Traceback (most recent call last):
  File "retrain.py", line 1326, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File
"D:\anaconda5.1\lib\site-packages\tensorflow\python\platform\app.py", line
126, in run
    _sys.exit(main(argv))
  File "retrain.py", line 989, in main
    class_count = len(image_lists.keys())
AttributeError: 'NoneType' object has no attribute 'keys'

**Comment by MauryaRitesh** [comment]
@hunaidkhan2000 You need to create the Images directory in tf_files and then fill two folders with the images of your face.
PLEASE watch the video carefully on YouTube!

**Comment by hunaidkhan2000** [comment]
yes brother i have created image files and folders in it ,

**Comment by MauryaRitesh** [comment]
Then created two other folders in the IMAGES FOLDER namely: your name and not your name.
Then, fill your face's images in the your name folder. and some other images not in your name folder.
Then run the training.

**Comment by hunaidkhan2000** [comment]
Tried that also still same error

**Comment by MauryaRitesh** [comment]
Start from Scratch again and watch the video carefully again!

**Comment by hunaidkhan2000** [comment]
i will try again and let you know. Thanks for the help
