### ISSUE TITLE
How to add UNknown label for untrained images

### ISSUE THREAD

**Issue by guruvishnuvardan** [MauryaRitesh/Face_ID#2]
HI,

I am using this code to identify unknown faces that are not trained, so  Can you please let me know, where to add "Unknown" label, so that I can take screen shot of those unknown persons to train later.

Thanks
Guru

**Comment by MauryaRitesh** [comment]
Create a folder with the name "unnamed" and fill it out with the images of face of random person.
Then, add your own face in another folder as suggested in the video(On YouTube).
Now run the training, after the training is completed.
Add some if statements in the last of label_image.py program.
E.G.:
After this line:

    labels = load_labels(label_file)

Add:

    if label[0]=='unnamed':
        import os
        if not os.path.exists('New Images'):
            os.mkdirs('New Images') #This directory should be under tf_files folder.

        from shutil import copyfile
        copyfile(file_name, "tf_files/New Images")

**Comment by guruvishnuvardan** [comment]
Thanks a ton :)
