### ISSUE TITLE
error running the last line of code

### ISSUE THREAD

**Issue by sriram317** [MauryaRitesh/Face_ID#3]
on running python -m scripts.retrain  --output_graph=tf_files/retrained_graph.pb  --output_labels=tf_files/retrained_labels.txt  --architecture=inception_v3  --image_dir=tf_files/images

error given is 
Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.

**Comment by MauryaRitesh** [comment]
Have a look at their guides:
https://www.tensorflow.org/install/pip
&&
https://www.tensorflow.org/install/#pip-installation-issues
